// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type Entry struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	GrowthStage string    `json:"growth_stage"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type EntryLink struct {
	SourceEntryID string    `json:"source_entry_id"`
	TargetEntryID string    `json:"target_entry_id"`
	UserID        string    `json:"user_id"`
	CreatedAt     time.Time `json:"created_at"`
}
