// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	DeleteEntry(ctx context.Context, id string) error
	GetEntryByID(ctx context.Context, id string) (Entry, error)
	ListEntriesByUser(ctx context.Context, userID string) ([]Entry, error)
	ListEntriesByUserSince(ctx context.Context, arg ListEntriesByUserSinceParams) ([]Entry, error)
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error)
}

var _ Querier = (*Queries)(nil)
